### ISSUE TITLE
top level images folder should be moved

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-management-portal#151]
There is a top-level images folder which is just used for documentation which should be moved to be a subfolder in docs.  It is confusing right now.

**Comment by Saumya-Sunder** [comment]
Hey @johnbent, all other component repos have images outside of the Doc folder. Should I be moving them all inside too? I thought that the structure was this hence I moved it out.

**Comment by Saumya-Sunder** [comment]
Hey @johnbent I am ignoring moving the image folder under docs folder as per our discussion on our Community Call on Thursday. @kupranay can you close this?

**Comment by johnbent** [comment]
Closing this for now.  We really should have all images in docs/images but not a major urgent need now.
