### ISSUE TITLE
Performance metrics stopped updating

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-management-portal#340]
[https://cortxcommunity.slack.com/archives/C01AQLMA75Y/p1619581025002100](https://cortxcommunity.slack.com/archives/C01AQLMA75Y/p1619581025002100)

"Hi guys, we had a strange last minute bug come up with our CORTX VM. Our performance metrics through the CORTX dashboard suddenly stopped displaying IOPS data over the last 24 hours, despite us having seen it this morning during testing and having written to CORTX several times throughout the day."

**Comment by johnbent** [comment]
It may just be that the scale is not adjusting:

![](https://user-images.githubusercontent.com/2047294/116346461-910f2d00-a7a7-11eb-97c4-9b688cff2c1c.png)

This is the read metrics and notice the scale is at 0.01.

![](https://user-images.githubusercontent.com/2047294/116346487-9d938580-a7a7-11eb-9c1f-fce627a51108.png)

This is the write metrics and notice the scale is at 10.  So maybe the data is there but not showing up.  Seems like the user might need the option to adjust the scale?

**Comment by kupranay** [comment]
GUI is being revamped. Hence no further work planned for this. Closing this issue

**Comment by cortx-admin** [comment]
> Sujit Singh commented in Jira Server:

Project cancelled.

**Comment by cortx-admin** [comment]
> Sujit Singh commented in Jira Server:

Project cancelled.

**Comment by cortx-admin** [comment]
> Sujit Singh commented in Jira Server:

Project under revamp
