### ISSUE TITLE
Please add code of conduct

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-management-portal#95]
@Saumya-Sunder please do this.  Please make sure it says opensource@seagate.com; that’s the one change to make from github provided.

**Comment by johnbent** [comment]
@Saumya-Sunder , can we close this yet?

**Comment by kupranay** [comment]
@Saumya-Sunder  please update this issue

**Comment by Saumya-Sunder** [comment]
Added https://github.com/Seagate/cortx-management-portal/pull/100 but there are conflicts. @kupranay I will resubmit it again. Could you please speed up the process for merging PRs? Because by the time they are approved, I have some sorta conflict or the other.

**Comment by Saumya-Sunder** [comment]
@kupranay could you close this issue? I am afraid that I do not have the access.

**Comment by Saumya-Sunder** [comment]
![image](https://user-images.githubusercontent.com/68316295/97872174-967d4480-1d3b-11eb-8ad7-346638a6f4db.png)
@kupranay please close this ticket as I do not see a option to close it.

**Comment by johnbent** [comment]
Closing since CoC has been added.
